#! usr/bin/env php
<?php

namespace Creational\ObjectPool;

require_once 'vendor/autoload.php';

$pool = new ObjectPool();

$pool->setObject(new City('London'));
$pool->setObject(new City('Berlin'));

printf("Your city is %s \n", $pool->getObject('London')->getName());
printf("Your city is %s \n", $pool->getObject('Berlin')->getName());
